fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.1.0'
    staging:
      repo: 'nanliu/staging'
      ref:  '1.0.3'
    postgresql:
      repo: 'puppetlabs/postgresql'
      ref: '3.4.1'
    java:
      repo: 'puppetlabs/java'
      ref: '1.1.1'
    firewall:
      repo: 'puppetlabs/firewall'
      ref: '1.1.3'
    apt:
      repo: 'puppetlabs/apt'
      ref: '1.5.2'
    concat:
      repo: 'puppetlabs/concat'
      ref: '1.0.4'

  symlinks:
    "bamboo": "#{source_dir}"
